# Generated by Django 3.0.4 on 2020-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_subscribe', models.EmailField(max_length=70, verbose_name='Пошта')),
            ],
            options={
                'verbose_name': 'підписку',
                'verbose_name_plural': 'Підписки',
            },
        ),
    ]
